In [1]:
import numpy as np
%config IPCompleter.greedy=True

### From Python list

In [6]:
my_list = [4,6,3,6,9]
my_list

[4, 6, 3, 6, 9]

In [24]:
arr = np.array(my_list)
arr

array([4, 6, 3, 6, 9])

In [33]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones

Generate arrays of zeros or ones

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## eye

Creates an identity matrix

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [39]:
np.random.rand(3)

array([0.0426186 , 0.52278056, 0.84314664])

In [62]:
np.random.rand(5,5)

array([[0.81343118, 0.28763495, 0.99945016, 0.82875995, 0.15364822],
       [0.9938896 , 0.95749036, 0.47397687, 0.79411262, 0.64684488],
       [0.35897375, 0.48142633, 0.47231018, 0.52320575, 0.15619217],
       [0.84995641, 0.05813062, 0.88816067, 0.39688408, 0.81930267],
       [0.02958664, 0.31240222, 0.01082359, 0.62662268, 0.45418126]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [40]:
np.random.randn(2)

array([-0.26423868, -0.5050423 ])

In [41]:
np.random.randn(5,5)

array([[-0.73116311, -0.38847704, -0.1771708 ,  0.02168212,  2.1844812 ],
       [-0.6404329 ,  0.1359724 , -0.31712112, -0.61164897, -0.28291701],
       [ 1.33815908,  0.12421381,  1.98014488, -0.02538036,  0.03044567],
       [ 0.63411173, -0.68412347,  1.21821212,  2.28075538, -0.97376904],
       [-0.46591983,  1.53497178,  1.01786128, -1.07486951,  0.06884583]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [42]:
np.random.randint(1,100)

32

In [44]:
np.random.randint(1,100,10)

array([ 1, 25, 72, 89, 23, 81, 35, 96, 70, 11])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [45]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [47]:
arr.dtype, arr.shape

(dtype('int32'), (25,))

In [48]:
np.array([[1],[2]]).shape

(2, 1)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
ranarr

array([21, 24, 16,  0, 36, 17, 23, 20, 20, 30])

## Reshape
Returns an array containing the same data with a new shape.
.reshape(...) . But the number of items should remain the same

In [49]:
np.random.rand(1,200).reshape(10,20)

array([[0.29017853, 0.30461515, 0.37673214, 0.72953127, 0.27798041,
        0.14415281, 0.45582399, 0.4487313 , 0.40723117, 0.28812289,
        0.04759519, 0.15008947, 0.31256253, 0.25280544, 0.19006043,
        0.41242635, 0.02203648, 0.63660487, 0.66896027, 0.0663078 ],
       [0.09619631, 0.05938158, 0.28208754, 0.24896921, 0.03994788,
        0.40059219, 0.87004398, 0.06767453, 0.62553714, 0.49770746,
        0.93443439, 0.20432565, 0.02568311, 0.21381438, 0.58260031,
        0.63887994, 0.32702641, 0.94595613, 0.94502881, 0.33551547],
       [0.77325045, 0.74393209, 0.36410998, 0.60671813, 0.36382545,
        0.89989602, 0.04191152, 0.68088254, 0.82881084, 0.10835843,
        0.07537029, 0.12437188, 0.2981368 , 0.06054684, 0.84259973,
        0.11059402, 0.16304018, 0.18561363, 0.022149  , 0.41590339],
       [0.78243119, 0.22167492, 0.24666129, 0.72772626, 0.68685834,
        0.56603526, 0.31539365, 0.83371432, 0.09415335, 0.94865123,
        0.25654718, 0.58817586, 0.24562061, 0

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr

array([ 8,  0,  7, 19, 19, 32, 31, 48,  2, 10])

In [53]:
ranarr.max() , ranarr.argmax()

(48, 7)

In [52]:
ranarr.mean()

17.6

In [74]:
np.max(ranarr)

36

In [85]:
np.min(ranarr), ranarr.argmin(0)

(0, 3)

In [76]:
ranarr.min()

0

In [54]:
np.sqrt(ranarr)

array([2.82842712, 0.        , 2.64575131, 4.35889894, 4.35889894,
       5.65685425, 5.56776436, 6.92820323, 1.41421356, 3.16227766])

### dtype

You can also grab the data type of the object in the array:
arr.dtype

In [86]:
arr.dtype

dtype('int32')

In [87]:
ranarr.dtype

dtype('int32')

In [88]:
len(ranarr)

10

In [95]:
ranarr.shape

(10,)

In [96]:
np.shape(ranarr)

(10,)

In [93]:
ranarr.reshape(2,5)

array([[21, 24, 16,  0, 36],
       [17, 23, 20, 20, 30]])