# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [12]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

- Get a value at an index

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[4]

4

- Get a value in a range

In [30]:
len(arr), arr, arr[-len(arr)]

(11, array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [36]:
arr[-1: 0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

- Set a value with index range broad cast a value.
- a[0:5] = 300

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 300

In [9]:
arr

array([300, 300, 300, 300, 300,   5,   6,   7,   8,   9,  10])

In [10]:
arr[:] = 300

In [11]:
arr

array([300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [23]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 11 into shape (2,5)

In [36]:
newarr = np.arange(0,50).reshape(5,10)

In [37]:
newarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
newarr[2:4,4:8]

array([[24, 25, 26, 27],
       [34, 35, 36, 37]])

In [18]:
newarr[1]

array([ 6,  7,  8,  9, 10])

In [20]:
newarr[0][1]

2

In [22]:
newarr[0,1]

2

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
b = arr > arr.mean()

In [29]:
b

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
arr[arr > arr.mean()]

array([ 6,  7,  8,  9, 10])

In [32]:
arr[(arr>4) & (arr<8)]

array([5, 6, 7])

In [33]:
(arr>4) & (arr<8)

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [10]:
bool_arr = arr>4

In [11]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [12]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])